# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Васичкин Павел
title: Java разработчик
email: pl.vasichkin@gmail.com
phone: +7 (926) 130-08-55
website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: pvasic
instagram_username: pv_asic
linkedin_username: pl.vasichkin
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
  - title: skype
    icon: fab fa-skype
    url: https://join.skype.com/invite/MbQSABeMa5hW

  - title: telegram
    icon: fab fa-telegram
    url: https://t.me/pvasic

# About Section
about_title: Личные качества
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Предприимчивость, инициативность и креативность.

content:
  - title: Квалификация
    layout: text
    content: |
      - <mark>Languages</mark> : Java, XML, SQL
      - <mark>Java Frameworks</mark> : Java (Time API, Streams), Spring (MVC, Security, JDBC, Data JPA, Boot), JPA (Hibernate), JUnit
      - <mark>DB</mark> : PostgreSQL, MySQL, HSQLDB, H2
      - <mark>JEE</mark> : Apache Tomcat
      - <mark>Технологии</mark> : REST, JDBC, JPA, Servlet, JSP/JSTL, AJAX, JWT
      - <mark>Инструменты</mark> : Git, Maven, IntelliJ IDEA
      - <mark>Навыки</mark> : применение концепций ООП, шаблонов проектирования, архитектурных шаблонов, UML, функционального программирования.
      - <mark>Английский</mark> : B1 – средний

  - title: Проекты # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Голосование за рестораны
        link: github.com/pvasic
        # link_text: Project Website
        additional_links:
          - title: pvasic/restaurant-voting
            icon: fab fa-github
            url: github.com/pvasic/restaurant-voting
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Проект разработан с нуля, являюсь архитектором, разработчиком и тестировщиком.
        description: | # this will include new lines to allow paragraphs
          Архитектура REST. Технологии Spring Boot, Data Jpa, JUnit, Open API Swager.

  - title: Опыт работы # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Javaops
        link: https://javaops.ru/
        # link_text: boringcompany.com
        sub_title: Стажировка Spring 5/JPA Enterprise
        caption: январь 2021 - настоящее время
        quote: >
          Участие в разработке Spring/JPA Enterprise приложения c авторизацией и правами доступа на основе ролей
        description: | # this will include new lines to allow paragraphs
          - реализация сохранения в базы Postgres и HSQLDB на основе Spring JDBC, JPA(Hibernate) и Spring Data JPA
          - реализация и тестирование REST и AJAX контроллеров
          - реализация клиента на Bootstrap (css/js), datatables, jQuery + plugins

  - title: # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: РКК «Энергия»
        link: https://javaops.ru/
        link_text: javaops.ru
        sub_title: Инженер
        caption: январь 2021 - настоящее время
        quote: >
          Поддержка полиграфического оборудования, Документооборот в КСЭД и 1С. Пуск-наладочные работы. Дизайн и вёрстка макетов в Adobe Photoshop, Illustrator, Indesign.
        description: | # this will include new lines to allow paragraphs
          - ввод в эксплуатацию нового оборудования FoilPrint 106, RisoA2, GUK-FA-36/2.
          - выявлены неисправности и ремонт оборудования HP Indigo press 3550, Riso 571E, Wohlenberg 92, EBA 721, МЛР 84С, GPM SURELAM PRO-500.
          - оптимизированы процессы: вёрстка макетов и спусков, программы печатных и резальных машин.

  - title:
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Джет
        link: http://www.jetpress.ru/
        link_text: jetpress.ru
        sub_title: Менеджер / SEO
        caption: ноябрь 2010 - февраль 2014
        quote: >
          Продажи. Управление заказами. SEO в Yandex Direct. Поддержка оборудования.
        description: | # this will include new lines to allow paragraphs
          - полностью переписал контекстную рекламу для полиграфической целевой аудитории.
          - Разработал калькулятор заказов в MathCad и Exel.

  - title:
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: RWS
        sub_title: Видеоинженер
        caption: август 2008 - ноябрь 2010
        quote: >
          Оцифровка материалов со съёмок, первичный монтаж. Цветокоррекция.
        description: | # this will include new lines to allow paragraphs
          - Работа с серверами, коммутаторами и записывающим оборудованием Sony и Panasonic.
          - Монтаж FinalCut Pro. Синхронизация звука. Цветокоррекция.


  - title: Образование # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Java Online Projects
        caption: январь 2021 - настоящее время
        sub_title: Архитектор / программист
        quote: >
          Java разработчик корпоративных приложений
        description: | # this will include new lines to allow paragraphs
          - 01/2021 — настояшее время. Стажировка – Java разработчик корпоративных приложений. Сертификат.
          - 01/2020 — 05/2020. Курс – Java разработчик веб-приложений. Сертификат с отличием.

  - title:  # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: «Специалист» при МГТУ им. Баумана
        caption: март 2018 - октябрь 2018
        sub_title: Программист
        quote: >

        description: | # this will include new lines to allow paragraphs
          - 08/2018 — 09/2018 Курс – Enterprise Java Beans. Сертификат.
          - 07/2018 — 08/2018 Курс – Java SE9. Уровень 2. Разработка клиент - серверных приложений. Сертификат.
          - 06/2018 — 07/2018 Курс – Java SE9. Уровень 1. Основы программирования. Сертификат.
          - 05/2018 — 06/2018 Курс – Программироване на языке С. Сертификат.
          - 04/2018 — 05/2018 Курс – Основы решения алгоритмических задач. Сертификат.
          - 01/2018 — 02/2018 Курс – Курс – Основы программирования и баз данных. Сертификат.

  - title:  # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Московский технический университет связи и информатики МТУСИ
        caption: 2011 - 2016
        sub_title: Специалист
        quote: >
          Факультет заочный.
        description: | # this will include new lines to allow paragraphs
          Специальность: сети связи и системы коммутации. Диплом о высшем образовании.

  - title:  # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: МГТУ им. Баумана
        caption: 2011 - 2016
        sub_title: Бакалавр
        quote: >
          Факультет: машиностроительные технологии
        description: | # this will include new lines to allow paragraphs
          Технологии сварки и диагностика.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
