# Site
repository: sproogen/resume-theme

# Content configuration version
version: 2

# Personal info
name: Васичкин Павел    Java разработчик
title: г. Москва, возраст 34 года,  высшее образование, опыт работы 1 год
email: pl.vasichkin@gmail.com
phone: +7 (926) 130-08-55

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: pvasic
instagram_username: pv_asic
#linkedin_username: pl.vasichkin
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
  - title: skype
    icon: fab fa-skype
    url: https://join.skype.com/invite/MbQSABeMa5hW

  - title: telegram
    icon: fab fa-telegram
    url: https://t.me/pvasic

# About Section
about_title: Личные качества
about_profile_image: images/profile.jpg
about_content: |  # this will include new lines to allow paragraphs
  Предприимчивость, инициативность, креативность.

content:
  - title: Квалификация
    layout: text
    content: |
      - <mark>Languages</mark> : Java, XML, SQL
      - <mark>Java Frameworks</mark> : Java (Time API, Streams), Spring (Boot, MVC, Security, JDBC, Data JPA), JPA (Hibernate), JUnit
      - <mark>DB</mark> : PostgreSQL, MySQL, HSQLDB, H2
      - <mark>JEE</mark> : Apache Tomcat
      - <mark>Технологии</mark> : REST, JDBC, JPA, Servlet, JSP/JSTL, AJAX, JWT, Swagger (OpenAPI 3.0)
      - <mark>Инструменты</mark> : Git, Maven, IntelliJ IDEA
      - <mark>Навыки</mark> : применение концепций ООП, шаблонов проектирования, архитектурных шаблонов, UML, функционального программирования.
      - <mark>Английский</mark> : A2

  - title: Проекты # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Голосование за рестораны
        sub_title: Архитектор, программист.
        caption: 10/2021 - настоящее время
        quote: >
          Личный проект. Разработка Spring/JPA Enterprise приложения c авторизацией и правами доступа на основе ролей. Только backend.
          Присутствует JUnit, Curl и Swagger тестирование.
        description: | # this will include new lines to allow paragraphs
          Архитектура REST. Технологии Spring Boot, Data Jpa, JUnit, Swagger (OpenAPI 3.0). DB H2.
        additional_links:
          - title: pvasic/restaurant-voting
            icon: fab fa-github
            url: github.com/pvasic/restaurant-voting

  - title:  # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Topjava от Javaops
        sub_title: Программист.
        caption: 09/2021 - настоящее время
        quote: >
          Участие в разработке Spring/JPA Enterprise приложения
        description: | # this will include new lines to allow paragraphs
          Технологии Spring, Data Jpa, AJAX, JUnit. DB: Postgres. Клиент на Bootstrap.
        additional_links:
          - title: pvasic/topjava
            icon: fab fa-github
            url: github.com/pvasic/topjava

          - title: topjavapvasic.herokuapp.com
            icon: fas fa-cloud
            url: topjavapvasic.herokuapp.com

  - title: Опыт работы # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Javaops
        link: http://javaops.ru/view/topjava
        link_text: javaops.ru/view/topjava
        sub_title: Стажировка Spring 5/JPA Enterprise
        caption: 01/2021 - настоящее время
        quote: >
          Участие в разработке Spring/JPA Enterprise приложения c авторизацией и правами доступа на основе ролей
                    на стеке Maven/ Spring MVC/ Security/ REST(Jackson)/ Java 8 Stream API
        description: | # this will include new lines to allow paragraphs
          - реализация сохранения в базы Postgres и HSQLDB на основе Spring JBDC, JPA(Hibernate) и Spring-Data-JPA
          - реализация и тестирование REST и AJAX контроллеров
          - реализация клиента на Bootstrap (css/js), datatables, jQuery + plugins
        additional_links:
          - title: pvasic/topjava
            icon: fab fa-github
            url: github.com/pvasic/topjava

  - title: # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: РКК «Энергия»
        sub_title: Инженер, дизайнер.
        caption: 02/2014 - настоящее время
        description: |
          Обслуживание и пуск-наладочные работы оборудования. Документооборот (1С, КСЭД). Дизайн и вёрстка макетов печатной продукции.

  - title: # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: «Джет»
        sub_title: Менеджер, SEO
        caption: 11/2010 - 02/2014
        description: |
          Переговоры с клиентами и рассчет комерческого предложения. SEO в Yandex Direct.

  - title: # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: «RWS»
        sub_title: Видеоинженер
        caption: 08/2008 - 11/2010
        description: |
          Видеомонтаж. Синхронизация звука. Цветокоррекция.

  - title: Образование # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Java Online Projects
        caption: 01/2021 - настоящее время
        sub_title: Архитектор / программист
        quote: >
          Java разработчик корпоративных приложений
        description: | # this will include new lines to allow paragraphs
          - 01/2021 - настояшее время. Стажировка – Java разработчик корпоративных приложений. Сертификат.
          - 01/2020 - 05/2020. Курс - Java разработчик веб-приложений. Сертификат с отличием.

  - title:  # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: «Специалист» при МГТУ им. Баумана
        caption: 01/2018 - 10/2018
        sub_title: Программист
        quote: >

        description: | # this will include new lines to allow paragraphs
          - 08/2018 - 09/2018 Курс - Enterprise Java Beans. Сертификат.
          - 07/2018 - 08/2018 Курс - Java SE9. Уровень 2. Разработка клиент - серверных приложений. Сертификат.
          - 06/2018 - 07/2018 Курс - Java SE9. Уровень 1. Основы программирования. Сертификат.
          - 05/2018 - 06/2018 Курс - Программироване на языке С. Сертификат.
          - 04/2018 - 05/2018 Курс - Основы решения алгоритмических задач. Сертификат.
          - 01/2018 - 02/2018 Курс - Основы программирования и баз данных. Сертификат.

  - title:  # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: МТУСИ, cвязи и информатики
        caption: 2011 - 2016
        sub_title: Специалист
        quote: >
          Факультет заочный.
        description: | # this will include new lines to allow paragraphs
          Специальность: сети связи и системы коммутации. Диплом о высшем образовании.

  - title:  # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: МГТУ им. Баумана
        caption: 2011 - 2016
        quote: >
          Факультет: машиностроительные технологии
        description: | # this will include new lines to allow paragraphs
          Специальность: технологии сварки и диагностики.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
